import { Equipment, MaintenanceTeam, MaintenanceRequest, DashboardStats } from '@/types';

export const mockTeams: MaintenanceTeam[] = [
  {
    id: 'team-1',
    name: 'Alpha Mechanics',
    specialization: 'Mechanical',
    members: ['John Smith', 'Maria Garcia', 'Ahmed Hassan'],
    activeRequests: 3,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'team-2',
    name: 'Circuit Masters',
    specialization: 'Electrical',
    members: ['Sarah Johnson', 'Michael Chen'],
    activeRequests: 2,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'team-3',
    name: 'IT Support',
    specialization: 'IT',
    members: ['David Kim', 'Emily Brown', 'Carlos Rodriguez', 'Lisa Wang'],
    activeRequests: 5,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'team-4',
    name: 'Climate Control',
    specialization: 'HVAC',
    members: ['Robert Taylor', 'Jennifer Lee'],
    activeRequests: 1,
    createdAt: new Date('2024-03-10'),
  },
];

export const mockEquipment: Equipment[] = [
  {
    id: 'eq-1',
    name: 'CNC Milling Machine',
    serialNumber: 'CNC-2024-001',
    category: 'Machinery',
    department: 'Production',
    teamId: 'team-1',
    location: 'Building A, Floor 1',
    purchaseDate: new Date('2022-06-15'),
    warrantyExpiry: new Date('2025-06-15'),
    condition: 'Good',
    usageHours: 4520,
    maintenanceCount: 12,
    isScrap: false,
    healthScore: 85,
    createdAt: new Date('2022-06-20'),
  },
  {
    id: 'eq-2',
    name: 'Forklift FT-200',
    serialNumber: 'FL-2023-042',
    category: 'Vehicles',
    department: 'Production',
    teamId: 'team-1',
    location: 'Warehouse B',
    purchaseDate: new Date('2023-03-10'),
    warrantyExpiry: new Date('2026-03-10'),
    condition: 'Excellent',
    usageHours: 1200,
    maintenanceCount: 4,
    isScrap: false,
    healthScore: 95,
    createdAt: new Date('2023-03-15'),
  },
  {
    id: 'eq-3',
    name: 'Dell Server R740',
    serialNumber: 'SRV-2024-088',
    category: 'Computers',
    department: 'IT',
    teamId: 'team-3',
    location: 'Data Center',
    purchaseDate: new Date('2024-01-05'),
    warrantyExpiry: new Date('2027-01-05'),
    condition: 'Excellent',
    usageHours: 8760,
    maintenanceCount: 2,
    isScrap: false,
    healthScore: 98,
    createdAt: new Date('2024-01-10'),
  },
  {
    id: 'eq-4',
    name: 'Industrial Drill Press',
    serialNumber: 'DP-2021-015',
    category: 'Tools',
    department: 'Production',
    teamId: 'team-1',
    location: 'Building A, Floor 2',
    purchaseDate: new Date('2021-08-20'),
    warrantyExpiry: new Date('2024-08-20'),
    condition: 'Fair',
    usageHours: 6800,
    maintenanceCount: 18,
    isScrap: false,
    healthScore: 65,
    createdAt: new Date('2021-08-25'),
  },
  {
    id: 'eq-5',
    name: 'HVAC Unit Central',
    serialNumber: 'HVAC-2020-003',
    category: 'Machinery',
    department: 'Production',
    teamId: 'team-4',
    location: 'Building A, Rooftop',
    purchaseDate: new Date('2020-05-12'),
    warrantyExpiry: new Date('2025-05-12'),
    condition: 'Good',
    usageHours: 15000,
    maintenanceCount: 24,
    isScrap: false,
    healthScore: 78,
    createdAt: new Date('2020-05-15'),
  },
  {
    id: 'eq-6',
    name: 'Electric Panel Board',
    serialNumber: 'EPB-2022-007',
    category: 'Machinery',
    department: 'Production',
    teamId: 'team-2',
    location: 'Building B, Basement',
    purchaseDate: new Date('2022-11-08'),
    warrantyExpiry: new Date('2027-11-08'),
    condition: 'Good',
    usageHours: 8760,
    maintenanceCount: 6,
    isScrap: false,
    healthScore: 88,
    createdAt: new Date('2022-11-10'),
  },
];

export const mockRequests: MaintenanceRequest[] = [
  {
    id: 'req-1',
    subject: 'CNC Machine Calibration',
    equipmentId: 'eq-1',
    type: 'Preventive',
    status: 'In Progress',
    scheduledDate: new Date('2024-12-28'),
    assignedTo: 'John Smith',
    teamId: 'team-1',
    description: 'Routine calibration and alignment check for CNC milling machine.',
    priority: 'Medium',
    createdAt: new Date('2024-12-20'),
    updatedAt: new Date('2024-12-27'),
  },
  {
    id: 'req-2',
    subject: 'Forklift Brake Replacement',
    equipmentId: 'eq-2',
    type: 'Corrective',
    status: 'New',
    scheduledDate: new Date('2024-12-29'),
    assignedTo: 'Maria Garcia',
    teamId: 'team-1',
    description: 'Brake pads showing signs of wear. Immediate replacement required.',
    priority: 'High',
    createdAt: new Date('2024-12-26'),
    updatedAt: new Date('2024-12-26'),
  },
  {
    id: 'req-3',
    subject: 'Server Firmware Update',
    equipmentId: 'eq-3',
    type: 'Preventive',
    status: 'New',
    scheduledDate: new Date('2024-12-30'),
    assignedTo: 'David Kim',
    teamId: 'team-3',
    description: 'Security patch and firmware update for Dell server.',
    priority: 'High',
    createdAt: new Date('2024-12-25'),
    updatedAt: new Date('2024-12-25'),
  },
  {
    id: 'req-4',
    subject: 'Drill Press Motor Repair',
    equipmentId: 'eq-4',
    type: 'Corrective',
    status: 'In Progress',
    scheduledDate: new Date('2024-12-27'),
    assignedTo: 'Ahmed Hassan',
    teamId: 'team-1',
    description: 'Motor making unusual noise. Requires inspection and potential replacement.',
    priority: 'Critical',
    createdAt: new Date('2024-12-24'),
    updatedAt: new Date('2024-12-27'),
  },
  {
    id: 'req-5',
    subject: 'HVAC Filter Replacement',
    equipmentId: 'eq-5',
    type: 'Preventive',
    status: 'Repaired',
    scheduledDate: new Date('2024-12-20'),
    assignedTo: 'Robert Taylor',
    teamId: 'team-4',
    description: 'Quarterly filter replacement and system cleaning.',
    priority: 'Low',
    createdAt: new Date('2024-12-15'),
    updatedAt: new Date('2024-12-20'),
  },
  {
    id: 'req-6',
    subject: 'Electric Panel Inspection',
    equipmentId: 'eq-6',
    type: 'Preventive',
    status: 'Repaired',
    scheduledDate: new Date('2024-12-18'),
    assignedTo: 'Sarah Johnson',
    teamId: 'team-2',
    description: 'Annual electrical safety inspection and thermal imaging.',
    priority: 'Medium',
    createdAt: new Date('2024-12-10'),
    updatedAt: new Date('2024-12-18'),
  },
  {
    id: 'req-7',
    subject: 'Old Conveyor Belt Disposal',
    equipmentId: 'eq-4',
    type: 'Corrective',
    status: 'Scrap',
    scheduledDate: new Date('2024-12-15'),
    assignedTo: 'John Smith',
    teamId: 'team-1',
    description: 'Equipment beyond repair. Marked for disposal.',
    priority: 'Low',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-15'),
  },
];

export const mockDashboardStats: DashboardStats = {
  totalEquipment: mockEquipment.length,
  activeRequests: mockRequests.filter(r => r.status === 'New' || r.status === 'In Progress').length,
  totalTeams: mockTeams.length,
  completedThisMonth: mockRequests.filter(r => r.status === 'Repaired').length,
};

export const getEquipmentById = (id: string) => mockEquipment.find(eq => eq.id === id);
export const getTeamById = (id: string) => mockTeams.find(team => team.id === id);
export const getRequestsByEquipmentId = (equipmentId: string) => 
  mockRequests.filter(req => req.equipmentId === equipmentId);
export const getRequestsByTeamId = (teamId: string) => 
  mockRequests.filter(req => req.teamId === teamId);
